### ISSUE TITLE
CLI: delete-testcase removes Java classes only

### ISSUE THREAD

**Issue by s-berg** [rockitconsulting/test.rockitizer#37]
Testcases, which are created with 
`cli create-test MyTest`
were deleted with 
`cli delete-testcase MyTest`

*Result:*
* Java-Test classes are deleted
* *testcases.yaml* still contains the testcase.

Version: **1.0.5.1**

**Comment by s-berg** [comment]
Sorry, i forgot
`cli sync `

Is it possible to start it automaticaly?

**Comment by rockitconsulting** [comment]
The command chaining is not yet supported, so please use the cli sync command. 
Cleaning the resources-<env>.yaml from obsolete configuration is not enabled, as it could follow to unwanted results, e.g. misspelled delete breaks the productive config. In the current implementation resources can be only added by sync.
