### ISSUE TITLE
cli create-env -> Log4j problem

### ISSUE THREAD

**Issue by s-berg** [rockitconsulting/test.rockitizer#38]
rockitizer version:     1.0.5.2
CLI version:               1.0
java:                          1.8.0_171
environment:             Windows 10

after the user (me) input the command 
_cli create-env LDEV_

the program throws an error: "No appenders could be found for logger"

see screenshot attached:

![image](https://user-images.githubusercontent.com/62023045/76959737-7d459600-691a-11ea-97b0-1be576258959.png)

**Possible solution:**

1. create an log4j.xml file and drop it into \bin folder
2. extend cli.bat (row 75) with entry: 
     .;bin\;

**Comment by rockitromansokunov** [comment]
This problem may be caused by the expected classes not having been compiled.

Please build the Maven project. Run Maven goal “update” for your Test.Rockitizer project. This will compile all necessary classes.

A recommended best practice would be to activate automatical project build in your IDE.
