### ISSUE TITLE
cli create-env LDEV -> FileNotFoundException

### ISSUE THREAD

**Issue by s-berg** [rockitconsulting/test.rockitizer#39]
rockitizer version:     1.0.5.2
CLI version:               1.0
java:                          1.8.0_171
environment:             Windows 10

after the user (me) input the command 
_cli create-env LDEV_

the program throws an error: "FileNotFoundException...... resources-LDEV.yaml"

see screenshot attached:

![image](https://user-images.githubusercontent.com/62023045/76960766-686a0200-691c-11ea-9c4b-c93f64d47a2e.png)

**Possible solution(s)**

1. run _cli create-env_ - without environment name
2. create following path in your project home:
     _**src/test/resources**_

**Comment by rockitromansokunov** [comment]
This problem may be caused by the expected classes not having been compiled.

Please build the Maven project. Run Maven goal “update” for your Test.Rockitizer project. This will compile all necessary classes.

A recommended best practice would be to activate automatical project build in your IDE.
