### ISSUE TITLE
cli create-test ->FileNotFoundException

### ISSUE THREAD

**Issue by s-berg** [rockitconsulting/test.rockitizer#40]
depends on Issue #39 

rockitizer version:     1.0.5.2
CLI version:               1.0
java:                          1.8.0_171
environment:             Windows 10

after the user (me) input the command 
_cli create-test Xml2XmlMq2MqTest_

the program throws an error: "FileNotFoundException .................. \resources.yaml"

see screenshot attached:

![image](https://user-images.githubusercontent.com/62023045/76962693-f85d7b00-691f-11ea-8adf-e12a27b03c64.png)

**Possible solution**
1. call
  _cli create-env_
without parameters

**Comment by yefymdmukh** [comment]
correct. configuration must exist in order to use the test plans cli
