### ISSUE TITLE
cli run all record --> ClassNotFoundException

### ISSUE THREAD

**Issue by s-berg** [rockitconsulting/test.rockitizer#42]
rockitizer version: 1.0.5.2
CLI version: 1.0
java: 1.8.0_171
environment: Windows 10
after the user (me) input the command
cli run all record
the program throws an error: "ClassNotFoundException.................."
see screenshot attached:

![image](https://user-images.githubusercontent.com/62023045/77061674-e987ce80-69da-11ea-9bd2-ca957e01ca64.png)

**Comment by rockitromansokunov** [comment]
This problem may be caused by the expected classes not having been compiled. 

Please build the Maven project. Run Maven goal “update” for your Test.Rockitizer project. This will compile all necessary classes.

A recommended best practice would be to activate automatical project build in your IDE.
