### ISSUE TITLE
JSONFileAssertion has problems with Json arrays

### ISSUE THREAD

**Issue by s-berg** [rockitconsulting/test.rockitizer#43]
rockitizer version: 1.0.5.2
CLI version: 1.0
java: 1.8.0_171
environment: Windows 10
IDE: IntelliJ

A valid JSON file  (RFC 8259) , with array cannot be processed by JSONFileAssertion.

`[Fatal Error] :1:56: Die Formatierungssteuerzeichen im Dokument nach dem Stammelement müssen syntaktisch korrekt sein.`

Input file:
`
{
   "persons": [
      {
         "name": "Alex Wurz",
         "old": 67
      },
      {
         "name": "Bertha Benz",
         "old": 171
      },
      {
         "name": "Arthur Conan Doyle",
         "old": 161
      }
   ]
}
`

The XML file generated by framework looks like:
`<persons><old>67</old><name>Alex Wurz</name></persons><persons><old>171</old><name>Bertha Benz</name></persons><persons><old>161</old><name>Arthur Conan Doyle</name></persons>`

**Comment by s-berg** [comment]
JSON Input file:

`{
    "persons": [
        {
            "name": "Alex Wurz",
            "old": 67
        },
        {
            "name": "Bertha Benz",
            "old": 171
        },
        {
            "name": "Arthur Conan Doyle",
            "old": 161
        }
    ]
}
`

**Comment by rockitromansokunov** [comment]
Issue was fixed.
