### ISSUE TITLE
Erwähnung von config.properties in CLI-Ausgabe

### ISSUE THREAD

**Issue by rockitromansokunov** [rockitconsulting/test.rockitizer#44]
Hallo Test.Rockitizer Team,

Im Record-Modus meldet „CLI run“ folgenden Text:

“INFO Assertions are only possible in replay mode. Set suite.mode in config.properties”.

Ich habe die config.properties nicht gefunden. Diese Datei ist eventuell nicht mehr benutzt. Löschen Sie mal bitte diese Zeile aus der Klasse, falls config.properties tatsächlich nicht mehr benutzt wird. 

Danke!

**Comment by rockitconsulting** [comment]
Fixed. Will be released with 1.0.5.4 
Kindly use 'cli run' with <record|replay|assert> modes or for use the 'mode' parameter value directly in JUnit run configurations in your IDE.
